### ISSUE TITLE
Fracturing procedure details

### ISSUE THREAD

**Issue by ttsesm** [Terascale-All-sensing-Research-Studio/MendNet#1]
Hi,

Thanks for sharing you work. Would be able to add some more details how to generate fractured shapes from scratch. Considering that you have already some point clouds, I would like to apply some fracturing where I would like to remove some parts from them.

Thanks.

**Comment by nikwl** [comment]
Hello! 

Sorry for the long delay, looks like I don't have notifications properly configured. If you'd like to use out our fracture method then I would look at [process_break.py](https://github.com/Terascale-All-sensing-Research-Studio/MendNet/blob/main/fracturing/processor/process_break.py). The function is callable from the command line and is actually pretty robust, you should be able to call it with the `-h` flag to see all of the passable parameters. It also has a function called `process` that you could import and use in your own code.

Hope this helps!

**Comment by ttsesm** [comment]
Hi @nikwl thanks for the feedback. No worries for the delay. I will check the script that you have pointed to me. It looks good.
